### ISSUE TITLE
Provide a prebuilt release file

### ISSUE THREAD

**Issue by hjf** [Tobias0110/RS41_gps_disciplined_oscillator#6]
Could you provide a flashable release file so installing MDK and friends won't be necessary?

**Comment by Tobias0110** [comment]
Hi, I will try to do that.

**Comment by pimol** [comment]
We're rooting for this.

**Comment by Tobias0110** [comment]
Sorry that I didn't work on this for a long time. Turns out the flash file was always available under:
`/MDK-ARM/GPS_clock/GPS_clock.hex`

**Comment by pimol** [comment]
Thanks a lot!

Pietro I2OIM

Il sab 9 mar 2024, 12:44 OE3TEC ***@***.***> ha scritto:
